### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by 0x5c0f** [A1k4id/channel_v3.json#2]
功能描述中本的方案不可用,我使用的fedora，其他操作系统未知，建议本地方案添加或修改为将channels 列值更新为channel_v3.json的下载地址
"channels":
	[
		"https://raw.githubusercontent.com/A1k4id/channel_v3.json/master/channel_v3.json"
	]

**Comment by A1k4id** [comment]
已更新 README 来避免歧义

**Comment by 0x5c0f** [comment]
额,可能你没有看懂我说的意思,本地配置方案当中的,使用的本地绝对路径在我这边是不能使用的,当然路径肯定是换成我自己的路径的. 我用的fedora29. 换成你在线地址就行了
